export interface RouteConfig {
  path: string;
  title: string;
  description: string;
  priority: number;
  changefreq: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
  type: 'main' | 'commercial' | 'location' | 'state';
}

export const MAIN_ROUTES: RouteConfig[] = [
  {
    path: '/',
    title: 'Omar SEO | Especialista em SEO, Google, Maps e GEO para IA',
    description: 'Omar SEO: estratégia completa de SEO técnico, SEO local, Google Maps, GEO, conteúdo e dados estruturados para ampliar a visibilidade de empresas no Google e em mecanismos de IA em Curitiba e região.',
    priority: 1.0,
    changefreq: 'daily',
    type: 'main',
  },
  {
    path: '/servicos',
    title: 'Serviços de SEO e Visibilidade Digital em Curitiba | Omar SEO',
    description: 'Conheça nosso leque de serviços em SEO técnico, SEO local, Google Maps, E-commerce, Link Building, CRO e GEO (Otimização para IA).',
    priority: 0.95,
    changefreq: 'weekly',
    type: 'main',
  },
  {
    path: '/servicos/consultoria-seo',
    title: 'Consultoria de SEO em Curitiba | Estratégia Orgânica B2B & B2C — Omar SEO',
    description: 'Consultoria de SEO estratégica com diagnóstico de mercado, arquitetura de informação e acompanhamento executivo para empresas em Curitiba.',
    priority: 0.9,
    changefreq: 'weekly',
    type: 'main',
  },
  {
    path: '/servicos/auditoria-seo',
    title: 'Auditoria SEO Técnica Completa em Curitiba | Omar SEO',
    description: 'Auditoria técnica minuciosa de indexação, Core Web Vitals, links quebrados e arquitetura de dados para o Google.',
    priority: 0.9,
    changefreq: 'weekly',
    type: 'main',
  },
  {
    path: '/servicos/setup-seo-tecnico',
    title: 'Setup de SEO Técnico & Performance para Web | Omar SEO',
    description: 'Implementação de SEO técnico de nível de engenharia: Schema.org, sitemaps dinâmicos, canonicals e pré-renderização estática.',
    priority: 0.9,
    changefreq: 'weekly',
    type: 'main',
  },
  {
    path: '/servicos/seo-local',
    title: 'SEO Local & Google Maps em Curitiba e RMC | Omar SEO',
    description: 'Posicione sua empresa no topo do Google Meu Negócio e atraia clientes nos bairros de Curitiba e cidades vizinhas.',
    priority: 0.9,
    changefreq: 'weekly',
    type: 'main',
  },
  {
    path: '/servicos/seo-ecommerce',
    title: 'SEO para E-commerce e Lojas Virtuais em Curitiba | Omar SEO',
    description: 'Otimização de lojas virtuais, arquitetura de categorias, dados estruturados de produtos e autoridade orgânica.',
    priority: 0.9,
    changefreq: 'weekly',
    type: 'main',
  },
  {
    path: '/servicos/link-building',
    title: 'Link Building & Digital PR de Alta Autoridade | Omar SEO',
    description: 'Aquisição de backlinks contextuais e reputação digital com técnicas éticas e focadas em transferência de autoridade.',
    priority: 0.9,
    changefreq: 'weekly',
    type: 'main',
  },
  {
    path: '/servicos/cro-otimizacao-conversao',
    title: 'CRO — Otimização da Taxa de Conversão em Curitiba | Omar SEO',
    description: 'Transforme tráfego orgânico em clientes pagantes com testes de fricção, copy persuasiva e fluxo de formulários.',
    priority: 0.9,
    changefreq: 'weekly',
    type: 'main',
  },
  {
    path: '/servicos/geo-otimizacao-ia',
    title: 'GEO — Otimização para Inteligência Artificial (ChatGPT/Gemini) | Omar SEO',
    description: 'Preparação do seu domínio e marca para ser citada nas respostas de ChatGPT, Gemini, Perplexity e Claude.',
    priority: 0.9,
    changefreq: 'weekly',
    type: 'main',
  },
  {
    path: '/sobre',
    title: 'Sobre Omar Skafi — Especialista em SEO, GEO e Visibilidade | Omar SEO',
    description: 'Conheça a trajetória de Omar Skafi, especialista em SEO técnico, SEO local e GEO em Curitiba com mais de 12 anos de atuação.',
    priority: 0.85,
    changefreq: 'monthly',
    type: 'main',
  },
  {
    path: '/metodo',
    title: 'Metodologia Omar SEO 4D | Framework Autoral de Visibilidade Digital',
    description: 'Conheça o Framework Omar SEO 4D: Engenharia de Código, Semântica HTML/Schema, Autoridade de Domínio e Otimização para IA (GEO).',
    priority: 0.85,
    changefreq: 'monthly',
    type: 'main',
  },
  {
    path: '/blog',
    title: 'Blog de SEO, GEO e Visibilidade Digital em Curitiba | Omar SEO',
    description: 'Artigos e tutoriais avançados sobre SEO técnico, SEO local, Google Maps, Core Web Vitals e inteligência artificial.',
    priority: 0.85,
    changefreq: 'weekly',
    type: 'main',
  },
  {
    path: '/seo-geo-aio',
    title: 'SEO + GEO + AIO: Como Ganhar Market Share com Previsibilidade | Suprema',
    description: 'Descubra em 30 segundos como a combinação de busca tradicional, modelos generativos e otimização semântica expande o market share com previsibilidade.',
    priority: 0.9,
    changefreq: 'weekly',
    type: 'main',
  },
  {
    path: '/blog/por-que-site-nao-aparece-no-google',
    title: 'Por Que Meu Site Não Aparece no Google? Rastreamento e Indexação | Omar SEO',
    description: 'Descubra a diferença crucial entre rastreamento, indexação e posicionamento. Entenda por que sites no ar continuam invisíveis no Google e como resolver.',
    priority: 0.85,
    changefreq: 'weekly',
    type: 'main',
  },
  {
    path: '/blog/google-ai-overviews-curitiba',
    title: 'Google AI Overviews e o Tráfego em Curitiba | Omar SEO',
    description: 'Entenda como as respostas geradas por IA no topo do Google mudaram a busca orgânica em Curitiba e como preparar seu site.',
    priority: 0.8,
    changefreq: 'monthly',
    type: 'main',
  },
  {
    path: '/blog/guia-seo-local-google-maps',
    title: 'Guia de SEO Local no Google Maps em Curitiba | Omar SEO',
    description: 'Passo a passo prático para otimizar o Perfil da Empresa no Google e dominar o Local 3-Pack nos bairros de Curitiba.',
    priority: 0.8,
    changefreq: 'monthly',
    type: 'main',
  },
  {
    path: '/blog/react-spa-prerender-seo-tecnico',
    title: 'React, SPAs e Pré-Renderização Estática para SEO | Omar SEO',
    description: 'Entenda por que aplicações React com Vite precisam de pré-renderização HTML para garantir 100% de indexação no Google.',
    priority: 0.8,
    changefreq: 'monthly',
    type: 'main',
  },
  {
    path: '/blog/core-web-vitals-inp-seo',
    title: 'INP nos Core Web Vitals e Impacto no SEO | Omar SEO',
    description: 'Como otimizar a métrica Interaction to Next Paint (INP) e manter seu site no verde nas avaliações do Google PageSpeed.',
    priority: 0.8,
    changefreq: 'monthly',
    type: 'main',
  },
  {
    path: '/seo',
    title: 'SEO Completo em Curitiba e Região | Omar SEO',
    description: 'Estratégia completa de SEO on-page, técnico, semântico e autoridade para destacar sua empresa nos motores de busca.',
    priority: 0.8,
    changefreq: 'weekly',
    type: 'main',
  },
  {
    path: '/google-maps',
    title: 'Otimização de Google Maps e Perfil da Empresa | Omar SEO',
    description: 'Posicione seu Perfil da Empresa no topo do Google Maps em Curitiba. Aumente chamadas, rotas e visitas locais.',
    priority: 0.8,
    changefreq: 'weekly',
    type: 'main',
  },
  {
    path: '/geo-ia',
    title: 'GEO (Generative Engine Optimization) para IAs | Omar SEO',
    description: 'Estratégias de GEO e dados estruturados para preparar a presença da sua marca para ChatGPT, Gemini, Perplexity e Claude.',
    priority: 0.8,
    changefreq: 'weekly',
    type: 'main',
  },
  {
    path: '/seo-tecnico',
    title: 'SEO Técnico, Schema.org e Performance Web | Omar SEO',
    description: 'Auditoria e ajuste técnico de velocidade, indexação, sitemaps, canonicals, Schema.org e renderização para o Google.',
    priority: 0.8,
    changefreq: 'weekly',
    type: 'main',
  },
  {
    path: '/resultados',
    title: 'Cases de Sucesso e Resultados de SEO | Omar SEO',
    description: 'Conheça relatórios, métricas de crescimento e projetos otimizados com a engenharia de visibilidade do Omar SEO.',
    priority: 0.8,
    changefreq: 'monthly',
    type: 'main',
  },
  {
    path: '/resultados/seo-advogados-planos-de-saude',
    title: 'Case SEO para Advogados de Planos de Saúde | Omar SEO',
    description: 'Case documentado de presença orgânica na primeira página do Google em consulta competitiva relacionada a advogados de planos de saúde em Curitiba.',
    priority: 0.85,
    changefreq: 'monthly',
    type: 'main',
  },
  {
    path: '/resultados/seo-celulares-curitiba-shopcell',
    title: 'Case SEO: Celulares em Curitiba | Shopcell + Omar SEO',
    description: 'Resultado orgânico documentado em uma busca comercial altamente competitiva do varejo de celulares em Curitiba.',
    priority: 0.85,
    changefreq: 'monthly',
    type: 'main',
  },
  {
    path: '/resultados/carplus-google-ai-overview-pneus-curitiba',
    title: 'Case GEO: Carplus na IA do Google em Curitiba | Omar SEO',
    description: 'Resultado documentado mostrando a Carplus Centro Automotivo entre as opções apresentadas pela Visão geral criada por IA do Google em uma pesquisa relacionada a pneus e oficinas em Curitiba.',
    priority: 0.85,
    changefreq: 'monthly',
    type: 'main',
  },
  {
    path: '/resultados/seo-local-ecoservy-corte-e-poda-curitiba',
    title: 'Case SEO Local: Corte e Poda no Google Maps | Omar SEO',
    description: 'Resultado documentado do SEO Local da Ecoservy em Curitiba. Primeiro resultado empresarial visível no bloco local do Google para a busca "corte e poda".',
    priority: 0.85,
    changefreq: 'monthly',
    type: 'main',
  },
  {
    path: '/resultados/comfort-divisorias-google-ia-curitiba',
    title: 'Case GEO: Comfort Divisórias na IA do Google | Omar SEO',
    description: 'Resultado documentado mostrando a Comfort Divisórias presente tanto na experiência generativa quanto nos resultados orgânicos do Google para uma pesquisa comercial sobre divisórias Eucatex em Curitiba.',
    priority: 0.85,
    changefreq: 'monthly',
    type: 'main',
  },
  {
    path: '/resultados/ky-drywall-google-ia-curitiba',
    title: 'Case GEO: KY Drywall na IA do Google em Curitiba | Omar SEO',
    description: 'Evidência real de presença da KY Drywall & Steel Frame na Visão geral criada por IA do Google para uma consulta comercial sobre empresas de drywall em Curitiba.',
    priority: 0.85,
    changefreq: 'monthly',
    type: 'main',
  },
  {
    path: '/resultados/seo-local-e-organico-alevinos-curitiba',
    title: 'Case SEO: Alevinos Curitiba no Google (Local e Orgânico) | Omar SEO',
    description: 'Evidência real de presença simultânea no bloco local (Google Maps) e nos resultados orgânicos para uma pesquisa de alta amplitude no segmento de piscicultura em Curitiba e Paraná.',
    priority: 0.85,
    changefreq: 'monthly',
    type: 'main',
  },
  {
    path: '/resultados/omega-revestimentos-acm-seo-geo-curitiba',
    title: 'Case SEO + GEO: Ômega Revestimentos e ACM | Omar SEO',
    description: 'Uma parceria de aproximadamente quatro anos com presença digital construída para um mercado competitivo de fachadas, revestimentos, ACM e estruturas.',
    priority: 0.85,
    changefreq: 'monthly',
    type: 'main',
  },
  {
    path: '/resultados/casas-pinheirao-google-ia-seo',
    title: 'Case GEO + SEO: Casas Pinheirão na IA do Google | Omar SEO',
    description: 'Resultado documentado para uma consulta conversacional de alta intenção sobre empresas que constroem casas pré-fabricadas diretamente no terreno do cliente.',
    priority: 0.85,
    changefreq: 'monthly',
    type: 'main',
  },
  {
    path: '/resultados/motofrete-centro-sao-paulo-seo',
    title: 'Case SEO: Motofrete no Centro de São Paulo | Omar SEO',
    description: 'Resultado orgânico documentado para uma pesquisa local diretamente relacionada ao serviço de motofrete/motoboy no Centro de São Paulo.',
    priority: 0.85,
    changefreq: 'monthly',
    type: 'main',
  },
  {
    path: '/resultados/rvm-persianas-florianopolis-seo',
    title: 'Case SEO: RVM Persianas em Florianópolis e Lagoa (SC) | Omar SEO',
    description: 'Presença orgânica e local documentada no Google para RVM Persianas em Florianópolis e Barra da Lagoa / Lagoa da Conceição (SC).',
    priority: 0.85,
    changefreq: 'monthly',
    type: 'main',
  },
  {
    path: '/resultados/consultora-loovi-google-seo',
    title: 'Case SEO: Consultora Loovi no Google | Omar SEO',
    description: 'Evidência real de presença orgânica para uma consulta diretamente relacionada à atividade profissional e à marca pesquisada.',
    priority: 0.85,
    changefreq: 'monthly',
    type: 'main',
  },
  {
    path: '/omar-skafi',
    title: 'Sobre Omar Skafi - Especialista em SEO e GEO | Omar SEO',
    description: 'Conheça Omar Skafi, especialista com sólida trajetória em SEO técnico, SEO local, Google Maps e GEO em Curitiba/PR.',
    priority: 0.8,
    changefreq: 'monthly',
    type: 'main',
  },
  {
    path: '/auditoria-seo',
    title: 'Auditoria SEO Gratuita e Diagnóstico de Site | Omar SEO',
    description: 'Solicite uma análise técnica completa do seu site e descubra os gargalos que impedem sua empresa de aparecer no Google.',
    priority: 0.9,
    changefreq: 'weekly',
    type: 'main',
  },
  {
    path: '/contato',
    title: 'Contato com Omar SEO | Atendimento Curitiba e RMC',
    description: 'Entre em contato direto com Omar Skafi pelo WhatsApp (41) 99272-1004 ou (41) 98700-1004 e agende seu diagnóstico.',
    priority: 0.85,
    changefreq: 'monthly',
    type: 'main',
  },
];

export const COMMERCIAL_ROUTES: RouteConfig[] = [
  {
    path: '/especialista-seo-curitiba',
    title: 'Especialista em SEO em Curitiba | Omar SEO',
    description: 'Contrate o melhor Especialista em SEO de Curitiba para posicionar sua empresa no topo das buscas do Google e mapas.',
    priority: 0.85,
    changefreq: 'weekly',
    type: 'commercial',
  },
  {
    path: '/consultor-seo-curitiba',
    title: 'Consultor de SEO em Curitiba | Estratégia de Visibilidade',
    description: 'Consultoria de SEO personalizada para empresas em Curitiba que buscam crescimento consistente em tráfego orgânico e vendas.',
    priority: 0.85,
    changefreq: 'weekly',
    type: 'commercial',
  },
  {
    path: '/seo-para-empresas',
    title: 'SEO para Empresas e B2B em Curitiba | Omar SEO',
    description: 'Estratégias de SEO corporativo para médias e grandes empresas dominarem termos de intenção de compra.',
    priority: 0.85,
    changefreq: 'weekly',
    type: 'commercial',
  },
  {
    path: '/seo-google-maps',
    title: 'Como Dominar o Google Maps em Curitiba | SEO Local',
    description: 'Técnicas avançadas de SEO no Perfil de Empresa do Google para se destacar na localização física e raio de atendimento.',
    priority: 0.85,
    changefreq: 'weekly',
    type: 'commercial',
  },
  {
    path: '/seo-para-chatgpt',
    title: 'SEO e GEO para ChatGPT e Motores de IA | Omar SEO',
    description: 'Saiba como estruturar sua marca e entidades digitais para ser citada nas respostas do ChatGPT e assistentes virtuais.',
    priority: 0.85,
    changefreq: 'weekly',
    type: 'commercial',
  },
  {
    path: '/seo-para-gemini',
    title: 'SEO para Gemini e Google AI Overviews | Omar SEO',
    description: 'Otimização voltada para as respostas geradas pelo Google Gemini e resumos com IA nas pesquisas.',
    priority: 0.85,
    changefreq: 'weekly',
    type: 'commercial',
  },
  {
    path: '/consultoria-seo',
    title: 'Consultoria de SEO Profissional e Diagnóstico | Omar SEO',
    description: 'Acompanhamento estratégico, auditorias periódicas e direcionamento técnico em SEO e visibilidade digital.',
    priority: 0.85,
    changefreq: 'weekly',
    type: 'commercial',
  },
  {
    path: '/seo-local-curitiba',
    title: 'SEO Local Curitiba: Guia Definitivo | Omar SEO',
    description: 'Aprenda como dominar o mercado local em Curitiba e bairros vizinhos atando SEO on-page com Google Perfil da Empresa.',
    priority: 0.85,
    changefreq: 'weekly',
    type: 'commercial',
  },
  {
    path: '/consultoria-seo-brasil',
    title: 'Consultoria de SEO no Brasil | Alcance Nacional | Omar SEO',
    description: 'Consultoria de SEO com abrangência nacional no Brasil. Omar Skafi desenvolve projetos de alta performance para empresas B2B, e-commerce e serviços.',
    priority: 0.85,
    changefreq: 'weekly',
    type: 'commercial',
  },
  {
    path: '/especialista-seo-brasil',
    title: 'Especialista em SEO e GEO no Brasil | Omar Skafi',
    description: 'Especialista em SEO e GEO com atuação nacional. Omar Skafi desenvolve estratégias avançadas de SEO técnico, Schema.org e posicionamento no Google e IAs.',
    priority: 0.85,
    changefreq: 'weekly',
    type: 'commercial',
  },
  {
    path: '/seo-curitiba-e-regiao',
    title: 'SEO em Curitiba e Região Metropolitana (~120 km) | Omar SEO',
    description: 'HUB Regional de SEO para Curitiba, Região Metropolitana e cidades no raio de 120km (Ponta Grossa, Lapa, Campo Largo, SJP, Paranaguá e Rio Negro).',
    priority: 0.85,
    changefreq: 'weekly',
    type: 'commercial',
  },
  {
    path: '/seo-vs-geo',
    title: 'SEO vs GEO: Qual a Diferença e Como Integrar? | Omar SEO',
    description: 'Entenda a diferença técnica entre SEO (Search Engine Optimization) e GEO (Generative Engine Optimization) e como combinar ambas as estratégias.',
    priority: 0.85,
    changefreq: 'weekly',
    type: 'commercial',
  },
  {
    path: '/geo-vs-aio',
    title: 'GEO vs AIO: Otimização para IAs Explicada | Omar SEO',
    description: 'Saiba o que é GEO (Generative Engine Optimization) e AIO (AI Optimization / Otimização para IA). Entenda as diferenças e como posicionar sua empresa.',
    priority: 0.85,
    changefreq: 'weekly',
    type: 'commercial',
  },
  {
    path: '/seo-para-ia',
    title: 'SEO para Inteligência Artificial & LLMs | Omar SEO',
    description: 'Descubra como aplicar SEO para Inteligência Artificial. Prepare seu site com dados estruturados, llms.txt e autoridade de entidade para ChatGPT e Gemini.',
    priority: 0.85,
    changefreq: 'weekly',
    type: 'commercial',
  },
  {
    path: '/consultor-seo-ou-agencia',
    title: 'Consultor de SEO ou Agência: Qual Escolher? | Omar SEO',
    description: 'Entenda os prós e contras de contratar um Consultor de SEO Especialista em comparação a uma Agência de Marketing Tradicional.',
    priority: 0.85,
    changefreq: 'weekly',
    type: 'commercial',
  },
  {
    path: '/dados-estruturados-schema',
    title: 'Especialista em Dados Estruturados Schema.org | Omar SEO',
    description: 'Otimização com dados estruturados Schema.org e JSON-LD. Garanta Rich Snippets e conectividade de entidade para Google e assistentes de IA.',
    priority: 0.85,
    changefreq: 'weekly',
    type: 'commercial',
  },
];

// Helper to assemble all routes including generated location routes
export function getAllRoutes(locationSlugs: string[]): RouteConfig[] {
  const locationRoutes: RouteConfig[] = locationSlugs.map((slug) => {
    const isState = slug.startsWith('parana') || slug.startsWith('santa-catarina') || slug.startsWith('rio-grande-do-sul');
    const formattedName = slug
      .split('-')
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' ');

    return {
      path: `/seo-${slug}`,
      title: `SEO em ${formattedName} | Especialista em SEO e Google Maps - Omar SEO`,
      description: `Estratégia de SEO local, Google Maps e visibilidade digital para empresas em ${formattedName}. Destaque sua marca na região com Omar SEO.`,
      priority: 0.7,
      changefreq: 'weekly',
      type: isState ? 'state' : 'location',
    };
  });

  return [...MAIN_ROUTES, ...COMMERCIAL_ROUTES, ...locationRoutes];
}
